### ISSUE TITLE
运行出错！

### ISSUE THREAD

**Issue by maxenergy** [PeterH0323/Smart_Construction#1]
你好，运行detect.py 出现这个错误
'Detect' object has no attribute 'm'
怎么处理？

**Comment by PeterH0323** [comment]
我之前升级了 pytorch 的版本到 1.6.0 出现了这个错误，我现在将 pytorch 降低到 1.5.1 可以解决，请试一下，
谢谢您的关注！如果解决了请告知下谢谢！

**Comment by eeric** [comment]
标签做好，可以用https://github.com/ultralytics/yolov5训练
