### ISSUE TITLE
yolov5x.pt能给一下吗，下不下来....

### ISSUE THREAD

**Issue by Bruce-Si** [PeterH0323/Smart_Construction#11]

**Comment by PeterH0323** [comment]
您好，我已将 `yolov5 V2.0` 官方权重上传到百度云，请查看 README.md : 中的 [官方权重](https://github.com/PeterH0323/Smart_Construction/blob/master/README.md#%E5%AE%98%E6%96%B9%E6%9D%83%E9%87%8D)，我先关闭这个 issue 了，后续如果有疑问欢迎继续提 issue 。
感谢您的关注！**如果帮到您请给个 star ✨✨✨，您的 star 是我最大的鼓励！**

**Comment by Bruce-Si** [comment]
看到啦，谢谢！
















在 2020-11-09 19:01:21，"PeterH0323" <notifications@github.com> 写道：

您好，我已将 yolov5 V2.0 官方权重上传到百度云，请查看 README.md : 中的 官方权重，我先关闭这个 issue 了，后续如果有疑问欢迎继续提 issue 。
感谢您的关注！如果帮到您请给个 star ✨✨✨，您的 star 是我最大的鼓励！

**Comment by PeterH0323** [comment]
😁
