### ISSUE TITLE
关于危险区域判断的问题

### ISSUE THREAD

**Issue by CoinCheung** [PeterH0323/Smart_Construction#12]
大佬好呀，

大概读了一遍代码，想确认一下我的理解是否正确。危险区域判断的方法是不是首先需要人工村注得到图片上的多边形的危险区域，然后看人的检测bbox的中心是否在危险区域多边形里面，如果在的话就认为人是处在危险区域了，也就是说危险区域不是使用算法得到的，是在每张图片上面预先定义好的?

**Comment by PeterH0323** [comment]
是的，危险区域是人为标注的。

因为考虑到危险区域千变万化，为了适配每种用户的需求，做了这样的设计。

**Comment by CoinCheung** [comment]
好的，另外请问你试过把conv和bn作fuse之后的准确率吗，看到代码里面有相关的部分。前几天我在别的任务上发现把一个训练好的模型的conv和bn做fuse之后准确率下降了，想请教你是否遇到过类似的问题呢?

**Comment by PeterH0323** [comment]
这个暂时没有试过，可以多多交流🤝

**Comment by CoinCheung** [comment]
好的，先关了啊，再次感谢!!!

**Comment by PeterH0323** [comment]
感谢您的关注，如果帮到您请给个 star ✨✨✨，您的 star 是我最大的鼓励！
