### ISSUE TITLE
70+epoch，验证集上P0.9，但是R只有0.03

### ISSUE THREAD

**Issue by xiaozheng666** [PeterH0323/Smart_Construction#14]
使用V3模型训练当前数据集是没问题的，但是使用V5为什么R很低

**Comment by jingzhouhuang** [comment]
same question,P is OK,but recall is low ,map0.5≈0.4

**Comment by PeterH0323** [comment]
将 `test.py` 入参的默认值 `conf_thres=0.4`,改大一点，我测试的时候将其设置为 `0.6`

**Comment by jingzhouhuang** [comment]
> 将 `test.py` 入参的默认值 `conf_thres=0.4`,改大一点，我测试的时候将其设置为 `0.6`

将你提供的helment_yolov5s.pt权重文件拿来测试，conf=0.6情况下，R还是只有0.4，还有其他地方需要修改吗

**Comment by xiaozheng666** [comment]
> 将 `test.py` 入参的默认值 `conf_thres=0.4`,改大一点，我测试的时候将其设置为 `0.6`

阈值越大 召回就更低了呀

**Comment by jingzhouhuang** [comment]
labels.npg里类别显示均衡吗，这边显示很不均衡

**Comment by eeric** [comment]
@PeterH0323 
whether coordinate calculation error to bbox of head, helmet?

**Comment by eeric** [comment]
@PeterH0323 
146th epoch: 
people bbox  P and R were better，while  P and R of head or helmet were worse.

as following:
1.training:
145/299     9.17G   0.04331    0.1072  0.004936    0.1554      7980       640:  99%|███████████████████████▋| 85/86    145/299     9.17G   0.04325    0.1071  0.004934    0.1552      1441       640:  99%|███████████████████████▋| 85/86    145/299     9.17G   0.04325    0.1071  0.004934    0.1552      1441       640: 100%|████████████████████████| 86/86    145/299     9.17G   0.04325    0.1071  0.004934    0.1552      1441       640: 100%|████████████████████████| 86/86 [00:49<00:00,  1.74it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95:  10%|█▎           | 1/10 [00:03<00:32,  3.63s/i               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95:  20%|██▌          | 2/10 [00:04<00:23,  2.92s/               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95:  30%|███▉         | 3/10 [00:06<00:17,  2.55s               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95:  40%|█████▏       | 4/10 [00:07<00:12,  2.0               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95:  50%|██████▌      | 5/10 [00:08<00:08,  1.               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95:  60%|███████▊     | 6/10 [00:08<00:05,  1               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95:  70%|█████████    | 7/10 [00:09<00:03,                 Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95:  80%|██████████▍  | 8/10 [00:09<00:01,               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95:  90%|███████████▋ | 9/10 [00:10<00:00               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|████████████| 10/10 [00:10<00:00               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|████████████| 10/10 [00:10<00:00,  1.05s/it]

2.verification：
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95
                 all         607    7.38e+04       0.893       0.352       0.342       0.232
              person         607    4.36e+03       0.846       0.798       0.776       0.536
                head         607    6.42e+04       0.903       0.128       0.123      0.0635
              helmet         607    5.23e+03       0.931       0.129       0.127      0.0965

**Comment by jingzhouhuang** [comment]
sorry,I solved the problem,mainly for anchors and data labels,get the same score with author,Thank you.

**Comment by chuanfuye** [comment]
> sorry,I solved the problem,mainly for anchors and data labels,get the same score with author,Thank you.

你好，我也遇到了同样的问题，请问你的（yolov5s模型基础）的训练脚本的epoch是多少呢，还有你自己kmeans跑出来的anchor数值大小是和作者README一样么，非常感谢你的回答

**Comment by PeterH0323** [comment]
我已更新文件 models/custom_data.yaml，更新了我经过kmeans的anchors和网络的深度和宽度，请试一下

**Comment by PeterH0323** [comment]
问题已经的到解决，先关闭这个 issue 了，后续如果有疑问的话欢迎继续提 issue ，感谢大家的关注和支持！

**Comment by eeric** [comment]
其实这个问题是正确使用文件：./data/gen_data/merge_data.py，因为在提取人体类别和坐标的时候会生成一次人体lable，如果操作多次，会重复生成人体lable。另一个原因是其它数据库的制作人体标签时，是不能和Safety-Helmet-Wearing-Dataset数据库合并的，而是单独标签。我迁移训练一轮效果：
                Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%
                 all     3.3e+03    2.07e+04       0.516       0.858       0.815        0.47
              person     3.3e+03    1.08e+04       0.408       0.811       0.729        0.44
                head     3.3e+03    9.18e+03        0.48       0.862       0.814       0.345
              helmet     3.3e+03         747       0.658       0.902       0.902       0.624

这里Safety-Helmet-Wearing-Dataset数据是把train和test合在一起（当然单幅图标签是独立的），大概69k，用val数据（约0.6k）测试。coco train提取的人体标签约6万多点，这样共7.1万训练集，验证集共33k。

所以，作者的测试结果是真实可信的，我没有用custom_yolov5.yaml，只用了yolov5s.yaml，当然也没有./data/gen_anchors/clauculate_anchors.py，聚类得出先验框。
