### ISSUE TITLE
train problem

### ISSUE THREAD

**Issue by eeric** [PeterH0323/Smart_Construction#16]
using yolov5s.pt as initial weights, it occurs error。
could you provide yolov5s.pt with torch-1.5.1 version？
thanks

**Comment by so-bright** [comment]
I try download the new weights in yolo Official website.  This is can train.

**Comment by eeric** [comment]
It's confusing that why author's operating environment was different from the YOLOV5 Official website.

**Comment by PeterH0323** [comment]
The YOLO version that I used is YOLOv5 v2.0. 

The latest version of YOLOv5 using Pytorch 1.6 to train, its pt file is not available for pytorch ＜= 1.5.x

I already uploaded the v2.0 pt file to baidu disk or you can download it in yolov5 official github page

**Comment by eeric** [comment]
@PeterH0323 
I tested README.md-官方权重-2020.11.09，they were not worked, so I trained, no used initial yolov5s.pt weights.

**Comment by PeterH0323** [comment]
Is your error message is about `zip` problem ? 
if it is, pls try to use the YOLOv5 V1.0 weight, you can download them in [here](https://github.com/ultralytics/yolov5/releases/tag/v1.0)

**Comment by eeric** [comment]
@PeterH0323 
not the error.
AttributeError: Can't get attribute 'Hardswish' on <module 'torch.nn.modules.activation' from '/home/yq/work-test/2020/Smart_Construction/pytorch-1.5.1/lib/python3.6/site-packages/torch/nn/modules/activation.py'>

**Comment by PeterH0323** [comment]
You need to use pytorch 1.5.x
Only the pytorch > 1.6 support the Hardswish

**Comment by PeterH0323** [comment]
Are you using my code to train?

**Comment by PeterH0323** [comment]
Are you using my code to train?
Only to pytorch >= 1.6 support `nn.Hardswish` , my code didn't use `nn.Hardswish`.

**Comment by eeric** [comment]
@PeterH0323 
torch-1.5.1 version
finally, I trained my yolov5s model no using official yolov5.pt
