### ISSUE TITLE
计算anchors

### ISSUE THREAD

**Issue by zhongwenkun886** [PeterH0323/Smart_Construction#17]
您好。你的说明里面需要自己计算新数据的anchors，但YOLOv5训练代码里面不是有自动计算新anchors的功能吗？训练参数 --noautoanchor ，utils/utils.py 里的 check_anchors 函数，这里应该会重新计算model里的 anchors。
不知道我的理解是否正确，谢谢指教。

**Comment by PeterH0323** [comment]
代码里面是有的，不需要执行那一个可选步骤
