### ISSUE TITLE
I downloaded 10 pictures at random. Why didn't I detect the class of person?

### ISSUE THREAD

**Issue by Xinlei-Ren** [PeterH0323/Smart_Construction#18]

**Comment by PeterH0323** [comment]
请问您运行的是哪个 `py` 文件，

- 如果使用 `area_detect.py`需要先配置危险区域，人体会在危险区域内被框出来，危险区域外的人不会被框出
- 如果使用 `detect.py`，可以将将所有人都框出来

**Comment by PeterH0323** [comment]
因为时间过久您未回复，这里先关闭了，如果后续还有疑问的话欢迎提 issue ，感谢您的关注 :-D
