### ISSUE TITLE
数据集增加分类

### ISSUE THREAD

**Issue by so-bright** [PeterH0323/Smart_Construction#19]
你好，能不能再详细点介绍下怎么数据集增加分类，还有您自己的数据集可以提供吗？
谢谢！！

**Comment by PeterH0323** [comment]
请看 README 最后一个小节😃

**Comment by PeterH0323** [comment]
因为时间过久您未回复，这里先关闭了，如果后续还有疑问的话欢迎提 issue ，感谢您的关注 :-D

**Comment by eeric** [comment]
https://github.com/PeterH0323/Smart_Construction/issues/27#issue-762423673
