### ISSUE TITLE
关于数据集类别的问题

### ISSUE THREAD

**Issue by GWwangshuo** [PeterH0323/Smart_Construction#2]
您好，十分感谢您开源的项目代码。请问您是如何在SHWD数据集中添加person的类别标注的，我印象中这个SHWD数据集中只有两类。

**Comment by PeterH0323** [comment]
我是使用 YOLO 自带的权重 x 来标出 SHWD 中的任务，在cmd指令中输入 detect.py 后面加上 --save-txt 会有每个输出图片的类别及anchor信息，将里面为 0 的类别（person）提取出来加入到 SHWD 中即可😁

**Comment by eeric** [comment]
可以使用coco数据，提取人体坐标
