### ISSUE TITLE
生成person类别问题

### ISSUE THREAD

**Issue by so-bright** [PeterH0323/Smart_Construction#22]
你好，我在进行person类别生成时遇到了
torch.nn.modules.module.ModuleAttributeError: 'Conv' object has no attribute '_non_persistent_buffers_set'
也是因为权重版本的问题吗

**Comment by PeterH0323** [comment]
请问您的 pytorch 版本是？

**Comment by so-bright** [comment]
我的是1.6

**Comment by PeterH0323** [comment]
请使用 `pytorch 1.5.x`

**Comment by so-bright** [comment]
好的，谢谢！！

**Comment by PeterH0323** [comment]
问题得到解决的话我先关闭 issue 了，如果后续有疑问的话欢迎继续提 issue ，感谢您的关注和支持！

**Comment by eeric** [comment]
https://github.com/PeterH0323/Smart_Construction/issues/27#issue-762423673
