### ISSUE TITLE
完全背景数据的问题

### ISSUE THREAD

**Issue by yeloiss** [PeterH0323/Smart_Construction#23]
请问，如果我的数据图片里有一些（完全无标注的）背景图，那我的label应该设置成什么样子呢？谢谢作者！

**Comment by PeterH0323** [comment]
可以使用的是 [精灵标注助手](http://www.jinglingbiaozhu.com/) 标注生成 xml 格式的标注文件，然后参考我的 `/data/gen_datagen_head_helmet.py` 进行转换

**Comment by yeloiss** [comment]
就是例如我的图片里没有person，没有头盔，任何target都类别都没有的话，我最后通过gen_datagen_head_helmet.py生成的txt文件，应该是空的是吗？谢谢作者解答！

**Comment by PeterH0323** [comment]
您需要根据您的业务进行改写

**Comment by yeloiss** [comment]
好的，谢谢您的解答！
