### ISSUE TITLE
python detect.py --save-txt --source ./自己数据集的文件目录 --weights ./weights/yolov5x.pt

### ISSUE THREAD

**Issue by so-bright** [PeterH0323/Smart_Construction#24]
C:\Users\10783\PycharmProjects\pythonProject\Smart_Construction-master>python detect.py --save-txt --source ./C:/Users/10783\PycharmProjects/pythonProject/Smart_Construction-master
/VOC2028/JPEGImages/ --weights ./weights/yolov5x.pt
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', img_size=640, iou_thres=0.5, output='inference/output', save_txt=True, source='./C:/Users/10783\\Pych
armProjects/pythonProject/Smart_Construction-master/VOC2028/JPEGImages/', update=False, view_img=False, weights=['./weights/yolov5x.pt'])
Using CUDA device0 _CudaDeviceProperties(name='GeForce GTX 1650', total_memory=4096MB)

C:\Users\10783\Anaconda3\lib\site-packages\torch\serialization.py:657: SourceChangeWarning: source code of class 'models.yolo.Model' has changed. you can retrieve the original source code
 by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\10783\Anaconda3\lib\site-packages\torch\serialization.py:657: SourceChangeWarning: source code of class 'models.yolo.Detect' has changed. you can retrieve the original source cod
e by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Fusing layers... Model Summary: 284 layers, 8.89222e+07 parameters, 8.89222e+07 gradients
Traceback (most recent call last):
  File "detect.py", line 161, in <module>
    detect()
  File "detect.py", line 52, in detect
    _ = model(img.half() if half else img) if device.type != 'cpu' else None  # run once
  File "C:\Users\10783\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\10783\PycharmProjects\pythonProject\Smart_Construction-master\models\yolo.py", line 99, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "C:\Users\10783\PycharmProjects\pythonProject\Smart_Construction-master\models\yolo.py", line 119, in forward_once
    x = m(x)  # run
  File "C:\Users\10783\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\10783\PycharmProjects\pythonProject\Smart_Construction-master\models\yolo.py", line 27, in forward
    x[i] = self.m[i](x[i])  # conv
  File "C:\Users\10783\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 593, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Detect' object has no attribute 'm'

你好，在pytorch1.5下  又遇到了这个问题   权重用的也是你v2.0的权重，这又是什么问题谢谢！

**Comment by PeterH0323** [comment]
请用列出您运行项目环境依赖库的 list

**Comment by PeterH0323** [comment]
- 我使用的指令：
`python detect.py --save-txt  --weights ./weights/yolov5x.pt`

- 输出的信息
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', img_size=640, iou_thres=0.5, output='inference/output', save_txt=True, source='inference/images', update=False, view_img=False, weights=['./weights/yolov5x.pt'])
Using CUDA device0 _CudaDeviceProperties(name='GeForce GTX 1660 Ti', total_memory=6144MB)

没有任何的问题，请问您使用的 `yolov5x.pt` 是不是我在 README.md 上面的百度云上传的权重，请使用我的权重进行训练，官方那个我再次查看了其`2.0`的权重也是压缩包了有可能会出现不兼容，**请使用我的 README.md 上面的百度云上传的权重**

**Comment by so-bright** [comment]
谢谢！！！感谢您耐心的解答 可以了

**Comment by PeterH0323** [comment]
问题得到解决的话我先关闭 issue 了，如果后续有疑问的话欢迎继续提 issue ，感谢您的关注和支持！
**如果帮到您请给个 star ✨✨✨，您的 star 是我最大的鼓励！**
