### ISSUE TITLE
训练的精度不正常

### ISSUE THREAD

**Issue by xiaonanQua** [PeterH0323/Smart_Construction#25]
你好，感谢你的开源！
我在按照你的文件配置之后，对你提供的安全帽进行训练，发现训练不正常。希望你能帮助我解决一下这个问题
![image](https://user-images.githubusercontent.com/29753887/99223057-bd00ac80-281e-11eb-96af-e4ed0edd8b50.png)

**Comment by PeterH0323** [comment]
请问您使用了 YOLOv5 进行了一遍人体识别了吗？
详见 [5. 增加数据集的分类](https://github.com/PeterH0323/Smart_Construction#5-%E5%A2%9E%E5%8A%A0%E6%95%B0%E6%8D%AE%E9%9B%86%E7%9A%84%E5%88%86%E7%B1%BB)

**Comment by PeterH0323** [comment]
因为时间过久您未回复，这里先关闭了，如果后续还有疑问的话欢迎提 issue ，感谢您的关注 :-D

**Comment by eeric** [comment]
https://github.com/PeterH0323/Smart_Construction/issues/27#issue-762423673
