### ISSUE TITLE
true test results about this project

### ISSUE THREAD

**Issue by eeric** [PeterH0323/Smart_Construction#27]
关于本项目训练效果一般问题，这其实是没有正确使用文件：./data/gen_data/merge_data.py，因为在提取人体类别和坐标的时候会生成一次人体标签文件，如果操作多次，会重复生成人体标签文件。另一个原因是若用其它数据库制作人体标签时，是不能和Safety-Helmet-Wearing-Dataset数据库合并的，而是各自数据要单独标签。我迁移训练一轮测试结果：

                Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%
                 all     3.3e+03    2.07e+04       0.516       0.858       0.815        0.47
              person     3.3e+03    1.08e+04       0.408       0.811       0.729        0.44
                head     3.3e+03    9.18e+03        0.48       0.862       0.814       0.345
              helmet     3.3e+03         747       0.658       0.902       0.902       0.624

这里Safety-Helmet-Wearing-Dataset数据是把train和test合在一起（当然单幅图像标签是独立的），大概数量69k，用val数据（约0.6k）测试。coco train提取的人体标签文件约6万多个，这样共7.1万训练集，验证集共33k，这里需要从生成的标签文件名对应到图像名文件，用作custom_data.yaml，这里建议用yolov5项目训练，https://github.com/ultralytics/yolov5。

所以，作者的测试结果是真实可信的，我没有用custom_yolov5.yaml，只用了yolov5s.yaml，当然也没有./data/gen_anchors/clauculate_anchors.py，聚类得出先验框。

**Comment by PeterH0323** [comment]
👍
