### ISSUE TITLE
why was not it successful to head detection?

### ISSUE THREAD

**Issue by eeric** [PeterH0323/Smart_Construction#28]
training one epoch result:

Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%
             all     3.3e+03    2.07e+04       0.516       0.858       0.815        0.47
          person     3.3e+03    1.08e+04       0.408       0.811       0.729        0.44
            head     3.3e+03    9.18e+03        0.48       0.862       0.814       0.345
          helmet     3.3e+03         747       0.658       0.902       0.902       0.624

but no head and helmet detection, only detecting person.
and head detection is not synchronized with person detection
if relating to anchors calculation or not.

**Comment by PeterH0323** [comment]
请检查下数据集，感谢您的关注😃
