### ISSUE TITLE
2 classes on SHWD and one clasee on coco

### ISSUE THREAD

**Issue by eeric** [PeterH0323/Smart_Construction#29]
if using head and helmet classes on SHWD, and coco person class to train, test result was not detect head and helmet, while only person detected.

**Comment by eeric** [comment]
Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95                   
                     all         607    1.43e+04       0.537       0.938       0.914       0.589
              person         607    4.36e+03       0.429       0.948        0.91       0.653
                head         607    9.18e+03       0.491       0.909       0.883       0.412
              helmet         607         747        0.69       0.959        0.95       0.701

上面用了SHWD的train集，共5457个标签，val集607个标签，使用yolov5s.pt预训练模型，训练了10 epoch，使用detect.py反而能检测到person，head了。难道是因为coco的person有6.3万标签，严重影响了3类检测模型的拟合程度，而使person检测极好，其它2类检测几乎没有呢？

**Comment by PeterH0323** [comment]
是不是你训练的程度还没有完全拟合，感谢您的关注  😃
