### ISSUE TITLE
about start train

### ISSUE THREAD

**Issue by mozeqiu** [PeterH0323/Smart_Construction#34]
hello when i start train ,i get a issue (FileNotFoundError: [Errno 2] No such file or directory: '/home/pytorch/Smart_Construction/score/labels/train.cache'
)
how about train.cache? please help!thanks!!

**Comment by PeterH0323** [comment]
If your file structure is correct, it will genrate `xxx.cache` automatically, please check your file structure. Thx

**Comment by PeterH0323** [comment]
Because no reply for a long time,  i close this issue. If you got question feather, please continue to post a issue, thank you for your attention! 😃
