### ISSUE TITLE
No such file or directory: '/home/imagedata/VOC2012/DataEnhancement/home/pytorch/Smart_Construction/labels/train.cache'

### ISSUE THREAD

**Issue by mozeqiu** [PeterH0323/Smart_Construction#35]
how about train.cache??i have no idea,please help!

**Comment by PeterH0323** [comment]
If your file structure is correct, it will genrate `xxx.cache` automatically, please check your file structure. Thx

**Comment by PeterH0323** [comment]
Because no reply for a long time, i close this issue. If you got question feather, please continue to post a issue, thank you for your attention! 😃

**Comment by Rocknroll194** [comment]
I also encountered the same problem ，so which file should I check or download the code again?
