### ISSUE TITLE
安全帽颜色检测

### ISSUE THREAD

**Issue by Zpadger** [PeterH0323/Smart_Construction#37]
小白请问大佬，如果我想对安全帽的颜色进行检测（红、黄、白、蓝），除了要改变classes，网络的结构需要作何改变吗？

`#训练集和验证集的 labels 和 image 文件的位置
train: ./score/images/train
val: ./score/images/val

#number of classes
nc: 6

#class names
names: ['person', 'no_helmet', 'red_helmet', 'yellow_helmet', 'blue_helmet', 'white_helmet']`

**Comment by PeterH0323** [comment]
只要改 classes 就行了，网络不要动

**Comment by PeterH0323** [comment]
因长时间为回复，先关闭本 issue 了，如果后续有任何疑问，欢迎继续提交 issue ，感谢您的关注

**Comment by Zpadger** [comment]
感谢大佬指点(这几天网络不好上不了github)
