### ISSUE TITLE
3类标签的数据集可以分享么？

### ISSUE THREAD

**Issue by gengyanlei** [PeterH0323/Smart_Construction#4]

**Comment by PeterH0323** [comment]
我是直接使用开源数据集 [Safety-Helmet-Wearing-Dataset](https://github.com/njvisionpower/Safety-Helmet-Wearing-Dataset) 来做的，您可以先使用 YOLOv5 自带的 yolov5x.pt 来进行任务的标记，将 `0` 的分类和 bbox 提取出来，然后结合到 SHWD 数据库里面的【安全帽】和【头】即可，感谢您的关注

**Comment by gengyanlei** [comment]
哦哦，也是，忘记这回事了。coco自带的person，谢啦，之前这么弄过。我还以为你自己标注的呢。

**Comment by PeterH0323** [comment]
好的，希望能够帮到您，感谢您的关注，问题解决了我先将这个 issue 关闭了，
如果帮到您，请给个 star ✨✨✨，您的 star 是我最大的鼓励！

**Comment by gengyanlei** [comment]
我开源了烟火数据集，互相star哟，嘿嘿

**Comment by PeterH0323** [comment]
已 star ✨ [fire-detect-yolov4](https://github.com/gengyanlei/fire-detect-yolov4) , 下次我有烟火需求我就用你的😁

**Comment by gengyanlei** [comment]
我的都没给你带来啥好处，你就star，我那么一说。你这么痛快，我也给你star了。我的那个烟火检测可以yolov4-5试试，实际应用比较多，据我了解需求不少呢

**Comment by PeterH0323** [comment]
哈哈哈，好的，我需要的时候试一试，谢谢😁
