### ISSUE TITLE
问一下大佬，数据集分类的问题

### ISSUE THREAD

**Issue by jhyscode** [PeterH0323/Smart_Construction#45]
原始的数据集只有people和hat两个分类，我看readme文件里面的custom_data.yaml的里面分类是三个分类，还有测试的图片也是三个分类，不知道大佬数据集这块是加入了自己标注的还是其他怎么处理的，希望解答一下，万分感谢！

**Comment by PeterH0323** [comment]
我自己加了人体，详细看最后一小节，谢谢

**Comment by jhyscode** [comment]
感谢大佬的答疑和回复！

**Comment by PeterH0323** [comment]
谢谢您的认可，如果帮到您请帮我点个 星星 🌟 🌟 🌟  谢谢！
