### ISSUE TITLE
where is the person class?

### ISSUE THREAD

**Issue by jinfagang** [PeterH0323/Smart_Construction#5]
the opensource one doesn't included person class, where is the person class?

**Comment by PeterH0323** [comment]
I use YOLO-x to classify person class, then use script to get '0'(person) class to merge SWHD dataset label.
You can see the detail in 【5. 增加数据集的分类】.😁

**Comment by jinfagang** [comment]
@PeterH0323 you are so clever!

**Comment by PeterH0323** [comment]
Thx.😁
If this project works for you, please give me a star which can make it be seen by more person who need it. ✨✨✨

**Comment by eeric** [comment]
use coco
