### ISSUE TITLE
增加数据集的分类具体怎么操作？可以分享下增加人体一项的数据集吗？

### ISSUE THREAD

**Issue by ttweixiao9999** [PeterH0323/Smart_Construction#70]
大佬，我想问下要增加人体这个类是不需要再训练模型？具体操作步骤可以讲详细点吗？可以分享下增加人体的数据集吗？是和之前的合并，还是单独的？

**Comment by ooooohhhhhxxx** [comment]
可以看下这 https://github.com/PeterH0323/Smart_Construction#5-增加数据集的分类   作者是使用yolov5官方的预训练模型先检测了一遍人体，将人体的标签与head合并得到人体这个类
