### ISSUE TITLE
python detect.py 得到错误：Exception: ./weights/yolov5x.pt missing, try downloading from https://drive.google.com/drive/folders/1Drs_Aiu7xx6S-ix95f9kNsA6ueKRpN2J

### ISSUE THREAD

**Issue by pengzhangzhi** [PeterH0323/Smart_Construction#9]
我不打算自己定义数据集，想直接拿过来用，于是使用代码：`python detect.py`，我没用过YOLO，所以不知道你后面那些内容到底是干嘛的，实在看不懂你的教程。
`--source   0  # webcam
                            file.jpg  # image 
                            file.mp4  # video
                            path/  # directory
                            path/*.jpg  # glob
                            rtsp://170.93.143.139/rtplive/470011e600ef003a004ee33696235daa  # rtsp stream
                            http://112.50.243.8/PLTV/88888888/224/3221225900/1.m3u8  # http stream
`
您能解释一下这个是干啥的么？最好附上一个示例。
结果得到了错误如下：
`(pytorch) PS C:\Users\彭张智computational AI\Desktop\Smart_Construction-master> python detect.py
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='inference/images', update=False, view_img=False, weights='./weights/yolov5x.pt')
Using CUDA device0 _CudaDeviceProperties(name='GeForce GTX 1660 Ti', total_memory=6144MB)

Downloading https://drive.google.com/uc?export=download&id=1mM8aZJlWTxOg7BZJvNUMrTnA2AbeCVzS as ./weights/yolov5x.pt... 系统找不到指定的路径。
Download error
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: 'storage.googleapis.com
Traceback (most recent call last):
  File "detect.py", line 161, in <module>
    detect()
  File "detect.py", line 23, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "C:\Users\彭张智computational AI\Desktop\Smart_Construction-master\models\experimental.py", line 132, in attempt_load
    google_utils.attempt_download(w)
  File "C:\Users\彭张智computational AI\Desktop\Smart_Construction-master\utils\google_utils.py", line 36, in attempt_download
    raise Exception(msg)
Exception: ./weights/yolov5x.pt missing, try downloading from https://drive.google.com/drive/folders/1Drs_Aiu7xx6S-ix95f9kNsA6ueKRpN2J`
我尝试去这个链接上自己下载，结果网很慢，翻墙出去也不行...
您有什么好的办法么？
另外，这个教程对我这样的小白不太友好，我实在看不太懂！
最后，感谢您开源的代码，这个模型很有用！谢谢！

**Comment by pengzhangzhi** [comment]
刚刚通过链接把文件下载过来了，使用  `python detect.py`

得到：
`
(pytorch) PS C:\Users\彭张智computational AI\Desktop\Smart_Construction-master> python detect.py
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='inference/images', update=False, view_img=False, weights='./weights/yolov5x.pt')
Using CUDA device0 _CudaDeviceProperties(name='GeForce GTX 1660 Ti', total_memory=6144MB)

Traceback (most recent call last):
  File "E:\Anaconda\envs\pytorch\lib\tarfile.py", line 189, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: 'py\nndarr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\pytorch\lib\tarfile.py", line 2297, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "E:\Anaconda\envs\pytorch\lib\tarfile.py", line 1093, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "E:\Anaconda\envs\pytorch\lib\tarfile.py", line 1035, in frombuf
    chksum = nti(buf[148:156])
  File "E:\Anaconda\envs\pytorch\lib\tarfile.py", line 191, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\pytorch\lib\site-packages\torch\serialization.py", line 555, in _load
    return legacy_load(f)
  File "E:\Anaconda\envs\pytorch\lib\site-packages\torch\serialization.py", line 466, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "E:\Anaconda\envs\pytorch\lib\tarfile.py", line 1589, in open
    return func(name, filemode, fileobj, **kwargs)
  File "E:\Anaconda\envs\pytorch\lib\tarfile.py", line 1619, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "E:\Anaconda\envs\pytorch\lib\tarfile.py", line 1482, in __init__
    self.firstmember = self.next()
  File "E:\Anaconda\envs\pytorch\lib\tarfile.py", line 2309, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "detect.py", line 161, in <module>
    detect()
  File "detect.py", line 23, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "C:\Users\彭张智computational AI\Desktop\Smart_Construction-master\models\experimental.py", line 133, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "E:\Anaconda\envs\pytorch\lib\site-packages\torch\serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "E:\Anaconda\envs\pytorch\lib\site-packages\torch\serialization.py", line 559, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: ./weights/yolov5x.pt is a zip archive (did you mean to use torch.jit.load()?)
(pytorch) PS C:\Users\彭张智computational AI\Desktop\Smart_Construction-master>
`

**Comment by PeterH0323** [comment]
您好，非常感谢您对我项目的关注。
您post的第二个问题是因为google云盘上面的是最新版本的 yolov5 的权重文件，是在 pytorch1.6 版本上进行训练的。然而我这个版本是 pytorch 1.5.x 上训练的，两者不兼容。
我在 RAEDNE.md 上面分享了我放在百度云盘的权重，请您使用那几个权重来进行推理，具体精度可看表格

**Comment by PeterH0323** [comment]
![image](https://user-images.githubusercontent.com/25873202/96735702-6a35ff80-13ee-11eb-82f2-98735af9fc1b.jpeg)
权重的位置在上图的底上的 百度云 超链接，我分享了3个权重，对应不同深度和宽度的网络

**Comment by PeterH0323** [comment]
运行的话，使用命令
```shell
python detect.py --source 图片文件(夹)路径 --weight 权重路径 
```
即可

**Comment by PeterH0323** [comment]
希望可以帮到您，我接受您的建议，后续会在 README.md中加入一些命令的例子。

期待您的回复，希望能够帮到您顺利跑起来😁

如果这个项目帮到您，请帮我点个 ✨ ，您的✨可以让这个好项目让更多的人看到，谢谢！

**Comment by pengzhangzhi** [comment]
> ![image](https://user-images.githubusercontent.com/25873202/96735702-6a35ff80-13ee-11eb-82f2-98735af9fc1b.jpeg)
> 权重的位置在 READNE.md 如图位于下方所示的 百度云 超链接，我分享了3个权重，对应不同深度和宽度的网络

那我应该使用哪权重文件？我下载过来什么都没有修改。任选一个么？

**Comment by pengzhangzhi** [comment]
那我从google drive 上下载的模型是要删掉么？

**Comment by PeterH0323** [comment]
您可以用 l 来测试下

是的，google云盘的那个可以删除掉，或者待用也行，如果使用我这个模型不需要那个权重文件。

**Comment by pengzhangzhi** [comment]
使用代码：`(pytorch) PS C:\Users\彭张智computational AI\Desktop\Smart_Construction-master> python detect.py --source .\test\test.jpg --weights .\weights\helmet_head_person_l.pt`，图片是网上下载的一张
![image](https://user-images.githubusercontent.com/59241275/96870804-040bb400-14a4-11eb-808d-4558991558e6.png)
报错信息如下：


(pytorch) PS C:\Users\彭张智computational AI\Desktop\Smart_Construction-master> python detect.py --weights .\weights\helmet_head_person_l.pt
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='inference/images', update=False, view_img=False, weights=['.\\weights\\helmet_head_person_l.pt'])
Using CUDA device0 _CudaDeviceProperties(name='GeForce GTX 1660 Ti', total_memory=6144MB)

E:\Anaconda\envs\pytorch\lib\site-packages\torch\serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
E:\Anaconda\envs\pytorch\lib\site-packages\torch\serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
E:\Anaconda\envs\pytorch\lib\site-packages\torch\serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Fusing layers... Model Summary: 236 layers, 4.73754e+07 parameters, 4.48868e+07 gradients
Traceback (most recent call last):
  File "detect.py", line 161, in <module>
    detect()
  File "detect.py", line 43, in detect
    dataset = LoadImages(source, img_size=imgsz)
  File "C:\Users\彭张智computational AI\Desktop\Smart_Construction-master\utils\datasets.py", line 85, in __init__
    raise Exception('ERROR: %s does not exist' % p)
Exception: ERROR: C:\Users\彭张智computational AI\Desktop\Smart_Construction-master\inference\images does not exist
(pytorch) PS C:\Users\彭张智computational AI\Desktop\Smart_Construction-master> python detect.py --source .\test\test.jpg --weights .\weights\helmet_head_person_l.pt    t
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='.\\test\\test.jpg', update=False, view_img=False, weights=['.\\weights\\helmet_head_person_l.pt'])
Using CUDA device0 _CudaDeviceProperties(name='GeForce GTX 1660 Ti', total_memory=6144MB)

E:\Anaconda\envs\pytorch\lib\site-packages\torch\serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
E:\Anaconda\envs\pytorch\lib\site-packages\torch\serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
E:\Anaconda\envs\pytorch\lib\site-packages\torch\serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Fusing layers... Model Summary: 236 layers, 4.73754e+07 parameters, 4.48868e+07 gradients
Traceback (most recent call last):
  File "detect.py", line 161, in <module>
    detect()
  File "detect.py", line 52, in detect
    _ = model(img.half() if half else img) if device.type != 'cpu' else None  # run once
  File "E:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\彭张智computational AI\Desktop\Smart_Construction-master\models\yolo.py", line 99, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "C:\Users\彭张智computational AI\Desktop\Smart_Construction-master\models\yolo.py", line 119, in forward_once
    x = m(x)  # run
  File "E:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\彭张智computational AI\Desktop\Smart_Construction-master\models\yolo.py", line 36, in forward
    y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + self.grid[i].to(x[i].device)) * self.stride[i]  # xy
RuntimeError: expected device cuda:0 and dtype Float but got device cuda:0 and dtype Half
(pytorch) PS C:\Users\彭张智computational AI\Desktop\Smart_Construction-master> python detect.py --source .\test\test.jpg --weights .\weights\helmet_head_person_l.pt
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='.\\test\\test.jpg', update=False, view_img=False, weights=['.\\weights\\helmet_head_person_l.pt'])
Using CUDA device0 _CudaDeviceProperties(name='GeForce GTX 1660 Ti', total_memory=6144MB)

E:\Anaconda\envs\pytorch\lib\site-packages\torch\serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
E:\Anaconda\envs\pytorch\lib\site-packages\torch\serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
E:\Anaconda\envs\pytorch\lib\site-packages\torch\serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Fusing layers... Model Summary: 236 layers, 4.73754e+07 parameters, 4.48868e+07 gradients
Traceback (most recent call last):
  File "detect.py", line 161, in <module>
    detect()
  File "detect.py", line 52, in detect
    _ = model(img.half() if half else img) if device.type != 'cpu' else None  # run once
  File "E:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\彭张智computational AI\Desktop\Smart_Construction-master\models\yolo.py", line 99, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "C:\Users\彭张智computational AI\Desktop\Smart_Construction-master\models\yolo.py", line 119, in forward_once
    x = m(x)  # run
  File "E:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\彭张智computational AI\Desktop\Smart_Construction-master\models\yolo.py", line 36, in forward
    y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + self.grid[i].to(x[i].device)) * self.stride[i]  # xy
RuntimeError: expected device cuda:0 and dtype Float but got device cuda:0 and dtype Half
```

**Comment by PeterH0323** [comment]
请问您用的 pytorch 版本是什么？

**Comment by PeterH0323** [comment]
我使用的是pytorch==1.5.1

**Comment by pengzhangzhi** [comment]
谢谢！已经可以使用了！非常感谢您的耐心回复！感激难以言表~

**Comment by PeterH0323** [comment]
好，非常感谢您对我这个项目的信任！

如果这个项目帮到您，请帮我点个 ✨ ，您的✨可以让这个好项目让更多的人看到，谢谢！

**Comment by pengzhangzhi** [comment]
：） 已经点了，加油！谢谢~

**Comment by PeterH0323** [comment]
😁
